<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.1 (Python 3.8.5 on win32)" generated="20200809 21:05:40.809" rpa="false">
<suite id="s1" name="TC01" source="C:\Projetos\Automation Practice\TestCases\TC01.robot">
<test id="s1-t1" name="Cenário 01: Garantir que ao clicar no header está direcionando para a homepage">
<kw name="Dado que esteja na tela HOME do site Automation Practice">
<msg timestamp="20200809 21:05:40.852" level="FAIL">No keyword with name 'Dado que esteja na tela HOME do site Automation Practice' found.</msg>
<status status="FAIL" starttime="20200809 21:05:40.852" endtime="20200809 21:05:40.852"></status>
</kw>
<status status="FAIL" starttime="20200809 21:05:40.849" endtime="20200809 21:05:40.852" critical="yes">No keyword with name 'Dado que esteja na tela HOME do site Automation Practice' found.</status>
</test>
<status status="FAIL" starttime="20200809 21:05:40.811" endtime="20200809 21:05:40.854"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="TC01">TC01</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200809 21:05:40.837" level="ERROR">Error in file 'C:\Projetos\Automation Practice\TestCases\TC01.robot' on line 2: Resource file 'C:\Projetos\Automation Practice\TestCases..\Resources\main.resource' does not exist.</msg>
<msg timestamp="20200809 21:05:40.839" level="ERROR">Error in file 'C:\Projetos\Automation Practice\TestCases\TC01.robot' on line 3: Resource file 'C:\Projetos\Automation Practice\TestCases..\Resources\Steps\Step_homepage.resource' does not exist.</msg>
</errors>
</robot>
